# ДЗ 5. CTE, Recursive CTE та Materialized View

У цій роботі я будую набір ознак клієнтів Olist для подальшого аналізу. Використовую PostgreSQL, послідовні CTE, рекурсію та матеріалізоване представлення. Для відтворюваності передбачив роботу з повним датасетом або навчальною stub-схемою.

## 1. Підключення до PostgreSQL і підготовка даних

Спочатку встановлюю залежності та запускаю локальний PostgreSQL. Запити виконую через одну допоміжну функцію, щоб результати було зручно переглядати у notebook.

In [1]:
%pip install -q psycopg2-binary sqlalchemy pandas kagglehub

In [2]:
import os
import subprocess
import pandas as pd
from sqlalchemy import create_engine, text
from IPython.display import display

# У Google Colab встановлюю системний PostgreSQL замість недоступного pgserver.
subprocess.run(['apt-get', 'update', '-qq'], check=True)
subprocess.run(['apt-get', 'install', '-y', '-qq', 'postgresql'], check=True)
subprocess.run(['service', 'postgresql', 'start'], check=True)

# Налаштовую локального користувача PostgreSQL для підключення з Python.
subprocess.run([
    'runuser', '-u', 'postgres', '--', 'psql', '-v', 'ON_ERROR_STOP=1',
    '-c', "ALTER USER postgres WITH PASSWORD 'colab_postgres';"
], check=True)

engine = create_engine(
    'postgresql+psycopg2://postgres:colab_postgres@localhost:5432/postgres',
    future=True
)

def run_sql(query, show=True):
    with engine.begin() as conn:
        result = conn.exec_driver_sql(query)
        if result.returns_rows:
            df = pd.DataFrame(result.fetchall(), columns=result.keys())
            if show:
                display(df)
            return df

with engine.connect() as conn:
    print(conn.execute(text('SELECT version()')).scalar_one())

PostgreSQL 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0, 64-bit

### Дані Olist

Спочатку пробую отримати реальні CSV через KaggleHub. Якщо завантаження недоступне, використовую детерміновану stub-схему з умови. Усі подальші запити працюють з однаковими typed-таблицями.

In [3]:
USE_STUB = False
try:
    import kagglehub
    dataset_dir = kagglehub.dataset_download('olistbr/brazilian-ecommerce')
    print('Olist CSV:', dataset_dir)
except Exception as exc:
    USE_STUB = True
    print('Kaggle недоступний, використовую stub:', str(exc)[:200])

Using Colab cache for faster access to the 'brazilian-ecommerce' dataset.
Olist CSV: /kaggle/input/brazilian-ecommerce

In [4]:
files = {
    'olist_customers_raw': 'olist_customers_dataset.csv',
    'olist_orders_raw': 'olist_orders_dataset.csv',
    'olist_order_items_raw': 'olist_order_items_dataset.csv',
    'olist_products_raw': 'olist_products_dataset.csv',
    'olist_sellers_raw': 'olist_sellers_dataset.csv',
}
if not USE_STUB:
    for table_name, file_name in files.items():
        df = pd.read_csv(os.path.join(dataset_dir, file_name))
        df.to_sql(table_name, engine, if_exists='replace', index=False, chunksize=10000)
        print(table_name, df.shape)
else:
    print('Пропускаю raw-завантаження: режим stub.')

olist_customers_raw (99441, 5)
olist_orders_raw (99441, 8)
olist_order_items_raw (112650, 7)
olist_products_raw (32951, 9)
olist_sellers_raw (3095, 4)

In [5]:
DDL = r"""
DROP TABLE IF EXISTS olist_order_items CASCADE;
DROP TABLE IF EXISTS olist_orders      CASCADE;
DROP TABLE IF EXISTS olist_customers   CASCADE;
DROP TABLE IF EXISTS olist_products    CASCADE;
DROP TABLE IF EXISTS olist_sellers     CASCADE;

CREATE TABLE olist_customers (
    customer_id              TEXT PRIMARY KEY,
    customer_unique_id       TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_city            TEXT,
    customer_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_orders (
    order_id                      TEXT PRIMARY KEY,
    customer_id                   TEXT NOT NULL REFERENCES olist_customers(customer_id),
    order_status                  TEXT NOT NULL,
    order_purchase_timestamp      TIMESTAMP NOT NULL,
    order_approved_at             TIMESTAMP,
    order_delivered_carrier_date  TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    CHECK (order_status IN (
        'created', 'approved', 'invoiced', 'processing',
        'shipped', 'delivered', 'unavailable', 'canceled'
    ))
);

CREATE TABLE olist_products (
    product_id                 TEXT PRIMARY KEY,
    product_category_name      TEXT,
    product_name_length        INTEGER CHECK (product_name_length IS NULL OR product_name_length >= 0),
    product_description_length INTEGER CHECK (product_description_length IS NULL OR product_description_length >= 0),
    product_photos_qty         INTEGER CHECK (product_photos_qty IS NULL OR product_photos_qty >= 0),
    product_weight_g           INTEGER CHECK (product_weight_g IS NULL OR product_weight_g >= 0),
    product_length_cm          INTEGER CHECK (product_length_cm IS NULL OR product_length_cm >= 0),
    product_height_cm          INTEGER CHECK (product_height_cm IS NULL OR product_height_cm >= 0),
    product_width_cm           INTEGER CHECK (product_width_cm IS NULL OR product_width_cm >= 0)
);

CREATE TABLE olist_sellers (
    seller_id              TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city            TEXT,
    seller_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_order_items (
    order_id            TEXT NOT NULL REFERENCES olist_orders(order_id),
    order_item_id       INTEGER NOT NULL,
    product_id          TEXT REFERENCES olist_products(product_id),
    seller_id           TEXT REFERENCES olist_sellers(seller_id),
    shipping_limit_date TIMESTAMP,
    price               NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    freight_value       NUMERIC(12, 2) CHECK (freight_value IS NULL OR freight_value >= 0),
    PRIMARY KEY (order_id, order_item_id)
);
"""
run_sql(DDL, show=False)
print("Typed-таблиці створено")

Typed-таблиці створено

In [6]:
if not USE_STUB:
    run_sql(r"""
INSERT INTO olist_customers
SELECT
    customer_id,
    customer_unique_id,
    customer_zip_code_prefix::INTEGER,
    customer_city,
    customer_state::CHAR(2)
FROM olist_customers_raw;

INSERT INTO olist_orders
SELECT
    order_id,
    customer_id,
    order_status,
    order_purchase_timestamp::TIMESTAMP,
    order_approved_at::TIMESTAMP,
    order_delivered_carrier_date::TIMESTAMP,
    order_delivered_customer_date::TIMESTAMP,
    order_estimated_delivery_date::TIMESTAMP
FROM olist_orders_raw;

INSERT INTO olist_products
SELECT
    product_id,
    product_category_name,
    product_name_lenght::INTEGER,
    product_description_lenght::INTEGER,
    product_photos_qty::INTEGER,
    product_weight_g::INTEGER,
    product_length_cm::INTEGER,
    product_height_cm::INTEGER,
    product_width_cm::INTEGER
FROM olist_products_raw;

INSERT INTO olist_sellers
SELECT
    seller_id,
    seller_zip_code_prefix::INTEGER,
    seller_city,
    seller_state::CHAR(2)
FROM olist_sellers_raw;

INSERT INTO olist_order_items
SELECT
    order_id,
    order_item_id::INTEGER,
    product_id,
    seller_id,
    shipping_limit_date::TIMESTAMP,
    price::NUMERIC(12, 2),
    freight_value::NUMERIC(12, 2)
FROM olist_order_items_raw;
""", show=False)
    print('Дані перенесено з raw у typed.')

Дані перенесено з raw у typed.

In [7]:
if USE_STUB:
    run_sql(r"""
DROP TABLE IF EXISTS olist_order_items CASCADE;
DROP TABLE IF EXISTS olist_orders      CASCADE;
DROP TABLE IF EXISTS olist_customers   CASCADE;
DROP TABLE IF EXISTS olist_products    CASCADE;
DROP TABLE IF EXISTS olist_sellers     CASCADE;

CREATE TABLE olist_customers (
    customer_id              TEXT PRIMARY KEY,
    customer_unique_id       TEXT NOT NULL,
    customer_zip_code_prefix INTEGER,
    customer_state           CHAR(2) NOT NULL,
    customer_city            TEXT
);

CREATE TABLE olist_orders (
    order_id                      TEXT PRIMARY KEY,
    customer_id                   TEXT NOT NULL REFERENCES olist_customers(customer_id),
    order_status                  TEXT NOT NULL,
    order_purchase_timestamp      TIMESTAMP NOT NULL,
    order_approved_at             TIMESTAMP,
    order_delivered_carrier_date  TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP,
    CHECK (order_status IN (
        'created', 'approved', 'invoiced', 'processing',
        'shipped', 'delivered', 'unavailable', 'canceled'
    ))
);

CREATE TABLE olist_products (
    product_id                 TEXT PRIMARY KEY,
    product_category_name      TEXT,
    product_name_length        INTEGER CHECK (product_name_length IS NULL OR product_name_length >= 0),
    product_description_length INTEGER CHECK (product_description_length IS NULL OR product_description_length >= 0),
    product_photos_qty         INTEGER CHECK (product_photos_qty IS NULL OR product_photos_qty >= 0),
    product_weight_g           INTEGER CHECK (product_weight_g IS NULL OR product_weight_g >= 0),
    product_length_cm          INTEGER CHECK (product_length_cm IS NULL OR product_length_cm >= 0),
    product_height_cm          INTEGER CHECK (product_height_cm IS NULL OR product_height_cm >= 0),
    product_width_cm           INTEGER CHECK (product_width_cm IS NULL OR product_width_cm >= 0)
);

CREATE TABLE olist_sellers (
    seller_id              TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city            TEXT,
    seller_state           CHAR(2) NOT NULL
);

CREATE TABLE olist_order_items (
    order_id            TEXT NOT NULL REFERENCES olist_orders(order_id),
    order_item_id       INTEGER NOT NULL,
    product_id          TEXT REFERENCES olist_products(product_id),
    seller_id           TEXT REFERENCES olist_sellers(seller_id),
    shipping_limit_date TIMESTAMP,
    price               NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
    freight_value       NUMERIC(12, 2) CHECK (freight_value IS NULL OR freight_value >= 0),
    PRIMARY KEY (order_id, order_item_id)
);

INSERT INTO olist_sellers (seller_id, seller_zip_code_prefix, seller_city, seller_state)
VALUES
    ('s_01', 10001, 'Sao Paulo', 'SP'),
    ('s_02', 20001, 'Rio de Janeiro', 'RJ'),
    ('s_03', 30001, 'Belo Horizonte', 'MG');

INSERT INTO olist_products (
    product_id, product_category_name,
    product_name_length, product_description_length,
    product_photos_qty, product_weight_g,
    product_length_cm, product_height_cm, product_width_cm
)
VALUES
    ('p_01', 'electronics', 10, 100, 2,  800, 20, 10, 15),
    ('p_02', 'electronics', 12, 120, 3, 1200, 25, 12, 18),
    ('p_03', 'home',        8,  90, 1, 1500, 30, 20, 25),
    ('p_04', 'home',        9,  80, 2,  700, 18, 10, 14),
    ('p_05', 'fashion',     7,  60, 1,  300, 10,  5,  8),
    ('p_06', 'beauty',      6,  50, 1,  200,  8,  4,  6),
    ('p_07', 'sport',       9,  70, 2,  900, 20, 15, 16);

INSERT INTO olist_customers (
    customer_id, customer_unique_id, customer_zip_code_prefix,
    customer_state, customer_city
)
SELECT
    'c_' || LPAD(n::TEXT, 3, '0'),
    'u_' || LPAD(((n - 1) % 25 + 1)::TEXT, 3, '0'),
    10000 + n,
    (ARRAY['SP', 'RJ', 'MG', 'BA', 'PR'])[(n % 5) + 1],
    'City' || (n % 10)
FROM generate_series(1, 30) AS n;

INSERT INTO olist_orders (
    order_id, customer_id, order_status,
    order_purchase_timestamp, order_approved_at,
    order_delivered_carrier_date, order_delivered_customer_date,
    order_estimated_delivery_date
)
SELECT
    'o_' || LPAD(n::TEXT, 3, '0'),
    'c_' || LPAD(((n % 30) + 1)::TEXT, 3, '0'),
    (ARRAY['delivered', 'delivered', 'delivered', 'canceled', 'shipped'])[(n % 5) + 1],
    TIMESTAMP '2024-01-01 00:00:00' + (n * INTERVAL '7 days'),
    TIMESTAMP '2024-01-01 00:00:00' + (n * INTERVAL '7 days') + INTERVAL '1 day',
    TIMESTAMP '2024-01-01 00:00:00' + (n * INTERVAL '7 days') + INTERVAL '3 days',
    TIMESTAMP '2024-01-01 00:00:00' + (n * INTERVAL '7 days') + INTERVAL '8 days',
    TIMESTAMP '2024-01-01 00:00:00' + (n * INTERVAL '7 days') + INTERVAL '10 days'
FROM generate_series(1, 50) AS n;

INSERT INTO olist_order_items (
    order_id, order_item_id, product_id, seller_id,
    shipping_limit_date, price, freight_value
)
SELECT
    'o_' || LPAD(((n - 1) % 50 + 1)::TEXT, 3, '0'),
    ((n - 1) / 50) + 1,
    'p_0' || ((n % 7) + 1),
    's_0' || ((n % 3) + 1),
    TIMESTAMP '2024-01-01 00:00:00' + (n * INTERVAL '7 days') + INTERVAL '5 days',
    (n % 200 + 10)::NUMERIC(12, 2),
    (n % 30 + 5)::NUMERIC(12, 2)
FROM generate_series(1, 100) AS n;
""", show=False)
    print('Створено навчальні дані: 30 customers, 50 orders, 100 order_items.')

In [8]:
run_sql("""
SELECT 'customers' AS table_name, COUNT(*) AS n_rows FROM olist_customers
UNION ALL SELECT 'orders', COUNT(*) FROM olist_orders
UNION ALL SELECT 'order_items', COUNT(*) FROM olist_order_items
UNION ALL SELECT 'products', COUNT(*) FROM olist_products
UNION ALL SELECT 'sellers', COUNT(*) FROM olist_sellers
ORDER BY table_name;
""")

    table_name  n_rows
0    customers   99441
1  order_items  112650
2       orders   99441
3     products   32951
4      sellers    3095

    table_name  n_rows
0    customers   99441
1  order_items  112650
2       orders   99441
3     products   32951
4      sellers    3095

## 2. CTE-chain pipeline

Я розділив розрахунок на окремі етапи: суми замовлень, RFM, квартальні когорти, ковзне середнє за 30 днів, частку скасувань та улюблену категорію. Для recency використовую дату з датасету, а не поточну дату.

In [9]:
run_sql("""
WITH
reference_date AS (-- Stage 0: stable reference date for historical dataset
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    -- Stage 1: orders + order_total + status
    SELECT
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    -- Stage 2: RFM features per customer
    SELECT
        s.customer_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_id, rd.as_of_date
),
stage3_cohort AS (
    -- Stage 3: cohort quarter from first order date
    SELECT
        r.*,
        DATE_TRUNC('quarter', r.first_order_date)::DATE AS cohort_quarter
    FROM stage2_rfm AS r
),
stage4_rolling_aov AS (
    -- Stage 4: rolling 30-day average order value per customer
    SELECT
        s.customer_id,
        s.order_id,
        s.order_ts,
        s.order_total,
        AVG(s.order_total) OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts
            RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
        )::NUMERIC(12, 2) AS avg_order_value_30d,
        ROW_NUMBER() OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts DESC, s.order_id DESC
        ) AS rn_recent
    FROM stage1_orders_total AS s
),
stage5_cancel_rate AS (
    -- Stage 5: cancellation rate per customer
    SELECT
        customer_id,
        AVG(
            CASE WHEN order_status = 'canceled' THEN 1.0 ELSE 0.0 END
        )::NUMERIC(6, 4) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),
stage6_category_revenue AS (
    -- Stage 6: revenue by customer and product category
    SELECT
        o.customer_id,
        COALESCE(p.product_category_name, '(unknown)') AS product_category_name,
        SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS o
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    LEFT JOIN olist_products AS p
        ON p.product_id = oi.product_id
    GROUP BY o.customer_id, COALESCE(p.product_category_name, '(unknown)')
),
stage7_preferred_category AS (
    -- Stage 7: preferred category per customer via top-1 ranking
    SELECT
        customer_id,
        product_category_name,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC, cr.product_category_name
            ) AS rn
        FROM stage6_category_revenue AS cr
    ) AS ranked
    WHERE rn = 1
)
SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0)::NUMERIC(12, 2) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(aov.avg_order_value_30d, 0)::NUMERIC(12, 2) AS avg_order_value_30d_recent,
    COALESCE(cancel.cancellation_rate, 0)::NUMERIC(6, 4) AS cancellation_rate,
    COALESCE(pc.product_category_name, '(none)') AS preferred_category,
    COALESCE(pc.category_revenue, 0)::NUMERIC(12, 2) AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON coh.customer_id = c.customer_id
LEFT JOIN stage4_rolling_aov AS aov
    ON aov.customer_id = c.customer_id
   AND aov.rn_recent = 1
LEFT JOIN stage5_cancel_rate AS cancel
    ON cancel.customer_id = c.customer_id
LEFT JOIN stage7_preferred_category AS pc
    ON pc.customer_id = c.customer_id
ORDER BY monetary DESC NULLS LAST, c.customer_id
LIMIT 20;
""")

,customer_id,customer_state,recency_days,frequency,monetary,first_order_date,cohort_quarter,avg_order_value_30d_recent,cancellation_rate,preferred_category,preferred_category_revenue
0,1617b1357756262bfa56ab541c47bc16,RJ,384,1,13664.08,2017-09-29,2017-07-01,13664.08,0.0000,telefonia_fixa,13664.08
1,ec5b2ba62e574342386871631fafd3fc,ES,95,1,7274.88,2018-07-15,2018-07-01,7274.88,0.0000,telefonia_fixa,7274.88
2,c6e2731c5b391845f6800c97401a43a9,MS,613,1,6929.31,2017-02-12,2017-01-01,6929.31,0.0000,utilidades_domesticas,6929.31
3,f48d464a0baaea338cb25f816991ab1f,ES,85,1,6922.21,2018-07-25,2018-07-01,6922.21,0.0000,pcs,6922.21
4,3fd6777bbce08a352fddd04e4a7cc8f6,SP,512,1,6726.66,2017-05-24,2017-04-01,6726.66,0.0000,artes,6726.66
5,05455dfa7cd02f13d132aa7a6a9729c6,MG,328,1,6081.54,2017-11-24,2017-10-01,6081.54,0.0000,agro_industria_e_comercio,6081.54
6,df55c14d1476a9a3467f131269c2477f,RJ,565,1,4950.34,2017-04-01,2017-04-01,4950.34,0.0000,eletroportateis,4950.34
7,e0a2412720e9ea4f26c1ac985f6a7358,GO,98,1,4809.44,2018-07-12,2018-07-01,4809.44,1.0000,cool_stuff,4809.44
8,24bbf5fd2f2e1b359ee7de94defc4a15,SP,548,1,4764.34,2017-04-18,2017-04-01,4764.34,0.0000,eletroportateis,4764.34
9,3d979689f636322c62418b6346b1c6d2,PB,118,1,4681.78,2018-06-22,2018-04-01,4681.78,0.0000,pcs,4681.78
10,1afc82cd60e303ef09b4ef9837c9505c,SP,76,1,4513.32,2018-08-03,2018-07-01,4513.32,0.0000,instrumentos_musicais,4513.32
11,cc803a2c412833101651d3f90ca7de24,RJ,140,1,4445.50,2018-05-31,2018-04-01,4445.50,0.0000,relogios_presentes,4445.50
12,926b6a6fb8b6081e00b335edaf578d35,DF,548,1,4194.76,2017-04-18,2017-04-01,4194.76,0.0000,eletroportateis,4194.76
13,35a413c7ca3c69756cb75867d6311c0d,MG,203,1,4175.26,2018-03-29,2018-01-01,4175.26,0.0000,consoles_games,4175.26
14,e9b0d0eb3015ef1c9ce6cf5b9dcbee9f,MG,81,1,4163.51,2018-07-29,2018-07-01,4163.51,0.0000,esporte_lazer,4163.51
15,3be2c536886b2ea4668eced3a80dd0bb,PA,621,1,4042.74,2017-02-04,2017-01-01,4042.74,0.0000,(unknown),4042.74
16,eb7a157e8da9c488cd4ddc48711f1097,SP,135,1,4034.44,2018-06-05,2018-04-01,4034.44,0.0000,bebes,4034.44
17,c6695e3b1e48680db36b487419fb0398,SP,579,1,4016.91,2017-03-18,2017-01-01,4016.91,0.0000,relogios_presentes,4016.91
18,31e83c01fce824d0ff786fcd48dad009,RJ,157,1,3979.55,2018-05-14,2018-04-01,3979.55,0.0000,ferramentas_jardim,3979.55
19,addc91fdf9c2b3045497b57fc710e820,MG,265,1,3826.80,2018-01-26,2018-01-01,3826.80,0.0000,esporte_lazer,3826.80

,customer_id,customer_state,recency_days,frequency,monetary,first_order_date,cohort_quarter,avg_order_value_30d_recent,cancellation_rate,preferred_category,preferred_category_revenue
0,1617b1357756262bfa56ab541c47bc16,RJ,384,1,13664.08,2017-09-29,2017-07-01,13664.08,0.0000,telefonia_fixa,13664.08
1,ec5b2ba62e574342386871631fafd3fc,ES,95,1,7274.88,2018-07-15,2018-07-01,7274.88,0.0000,telefonia_fixa,7274.88
2,c6e2731c5b391845f6800c97401a43a9,MS,613,1,6929.31,2017-02-12,2017-01-01,6929.31,0.0000,utilidades_domesticas,6929.31
3,f48d464a0baaea338cb25f816991ab1f,ES,85,1,6922.21,2018-07-25,2018-07-01,6922.21,0.0000,pcs,6922.21
4,3fd6777bbce08a352fddd04e4a7cc8f6,SP,512,1,6726.66,2017-05-24,2017-04-01,6726.66,0.0000,artes,6726.66
5,05455dfa7cd02f13d132aa7a6a9729c6,MG,328,1,6081.54,2017-11-24,2017-10-01,6081.54,0.0000,agro_industria_e_comercio,6081.54
6,df55c14d1476a9a3467f131269c2477f,RJ,565,1,4950.34,2017-04-01,2017-04-01,4950.34,0.0000,eletroportateis,4950.34
7,e0a2412720e9ea4f26c1ac985f6a7358,GO,98,1,4809.44,2018-07-12,2018-07-01,4809.44,1.0000,cool_stuff,4809.44
8,24bbf5fd2f2e1b359ee7de94defc4a15,SP,548,1,4764.34,2017-04-18,2017-04-01,4764.34,0.0000,eletroportateis,4764.34
9,3d979689f636322c62418b6346b1c6d2,PB,118,1,4681.78,2018-06-22,2018-04-01,4681.78,0.0000,pcs,4681.78
10,1afc82cd60e303ef09b4ef9837c9505c,SP,76,1,4513.32,2018-08-03,2018-07-01,4513.32,0.0000,instrumentos_musicais,4513.32
11,cc803a2c412833101651d3f90ca7de24,RJ,140,1,4445.50,2018-05-31,2018-04-01,4445.50,0.0000,relogios_presentes,4445.50
12,926b6a6fb8b6081e00b335edaf578d35,DF,548,1,4194.76,2017-04-18,2017-04-01,4194.76,0.0000,eletroportateis,4194.76
13,35a413c7ca3c69756cb75867d6311c0d,MG,203,1,4175.26,2018-03-29,2018-01-01,4175.26,0.0000,consoles_games,4175.26
14,e9b0d0eb3015ef1c9ce6cf5b9dcbee9f,MG,81,1,4163.51,2018-07-29,2018-07-01,4163.51,0.0000,esporte_lazer,4163.51
15,3be2c536886b2ea4668eced3a80dd0bb,PA,621,1,4042.74,2017-02-04,2017-01-01,4042.74,0.0000,(unknown),4042.74
16,eb7a157e8da9c488cd4ddc48711f1097,SP,135,1,4034.44,2018-06-05,2018-04-01,4034.44,0.0000,bebes,4034.44
17,c6695e3b1e48680db36b487419fb0398,SP,579,1,4016.91,2017-03-18,2017-01-01,4016.91,0.0000,relogios_presentes,4016.91
18,31e83c01fce824d0ff786fcd48dad009,RJ,157,1,3979.55,2018-05-14,2018-04-01,3979.55,0.0000,ferramentas_jardim,3979.55
19,addc91fdf9c2b3045497b57fc710e820,MG,265,1,3826.80,2018-01-26,2018-01-01,3826.80,0.0000,esporte_lazer,3826.80

## 3. Recursive CTE: referral chain

У вихідному Olist немає реферальних зв’язків, тому створюю їх синтетично. Рекурсивний запит показує глибину дерева та шлях до клієнта.

In [10]:
run_sql("""
DROP TABLE IF EXISTS hw5_referrals CASCADE;

CREATE TABLE hw5_referrals (
    referrer_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_customer_id TEXT NOT NULL REFERENCES olist_customers(customer_id),
    referred_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (referred_customer_id),
    CHECK (referrer_customer_id <> referred_customer_id)
);

WITH ordered_customers AS (
    SELECT
        customer_id,
        ROW_NUMBER() OVER (ORDER BY customer_id) AS rn
    FROM olist_customers
    ORDER BY customer_id
    LIMIT 10
)
INSERT INTO hw5_referrals (referrer_customer_id, referred_customer_id)
SELECT
    prev.customer_id AS referrer_customer_id,
    nxt.customer_id AS referred_customer_id
FROM ordered_customers AS prev
JOIN ordered_customers AS nxt
    ON nxt.rn = prev.rn + 1
ON CONFLICT (referred_customer_id) DO NOTHING;

SELECT *
FROM hw5_referrals
ORDER BY referrer_customer_id, referred_customer_id;
""")

,referrer_customer_id,referred_customer_id,referred_at
0,00012a2ce6f8dcda20d059ce98491703,000161a058600d5901f007fab4c27140,2026-10-27 16:38:52.692770+00:00
1,000161a058600d5901f007fab4c27140,0001fd6190edaaf884bcaf3d49edf079,2026-10-27 16:38:52.692770+00:00
2,0001fd6190edaaf884bcaf3d49edf079,0002414f95344307404f0ace7a26f1d5,2026-10-27 16:38:52.692770+00:00
3,0002414f95344307404f0ace7a26f1d5,000379cdec625522490c315e70c7a9fb,2026-10-27 16:38:52.692770+00:00
4,000379cdec625522490c315e70c7a9fb,0004164d20a9e969af783496f3408652,2026-10-27 16:38:52.692770+00:00
5,0004164d20a9e969af783496f3408652,000419c5494106c306a97b5635748086,2026-10-27 16:38:52.692770+00:00
6,000419c5494106c306a97b5635748086,00046a560d407e99b969756e0b10f282,2026-10-27 16:38:52.692770+00:00
7,00046a560d407e99b969756e0b10f282,00050bf6e01e69d5c0fd612f1bcfb69c,2026-10-27 16:38:52.692770+00:00
8,00050bf6e01e69d5c0fd612f1bcfb69c,000598caf2ef4117407665ac33275130,2026-10-27 16:38:52.692770+00:00

,referrer_customer_id,referred_customer_id,referred_at
0,00012a2ce6f8dcda20d059ce98491703,000161a058600d5901f007fab4c27140,2026-10-27 16:38:52.692770+00:00
1,000161a058600d5901f007fab4c27140,0001fd6190edaaf884bcaf3d49edf079,2026-10-27 16:38:52.692770+00:00
2,0001fd6190edaaf884bcaf3d49edf079,0002414f95344307404f0ace7a26f1d5,2026-10-27 16:38:52.692770+00:00
3,0002414f95344307404f0ace7a26f1d5,000379cdec625522490c315e70c7a9fb,2026-10-27 16:38:52.692770+00:00
4,000379cdec625522490c315e70c7a9fb,0004164d20a9e969af783496f3408652,2026-10-27 16:38:52.692770+00:00
5,0004164d20a9e969af783496f3408652,000419c5494106c306a97b5635748086,2026-10-27 16:38:52.692770+00:00
6,000419c5494106c306a97b5635748086,00046a560d407e99b969756e0b10f282,2026-10-27 16:38:52.692770+00:00
7,00046a560d407e99b969756e0b10f282,00050bf6e01e69d5c0fd612f1bcfb69c,2026-10-27 16:38:52.692770+00:00
8,00050bf6e01e69d5c0fd612f1bcfb69c,000598caf2ef4117407665ac33275130,2026-10-27 16:38:52.692770+00:00

In [11]:
run_sql("""
WITH RECURSIVE referral_depth AS (
    -- ANCHOR: root customers, які не були referred іншими customers
    SELECT
        c.customer_id,
        1 AS depth,
        ARRAY[c.customer_id]::TEXT[] AS path_ids,
        c.customer_id::TEXT AS path_text
    FROM olist_customers AS c
    WHERE NOT EXISTS (
        SELECT 1
        FROM hw5_referrals AS r
        WHERE r.referred_customer_id = c.customer_id
    )

    UNION ALL

    -- RECURSIVE: перейти від referrer до його referred customers
    SELECT
        r.referred_customer_id AS customer_id,
        rd.depth + 1 AS depth,
        rd.path_ids || r.referred_customer_id AS path_ids,
        rd.path_text || ' -> ' || r.referred_customer_id AS path_text
    FROM hw5_referrals AS r
    JOIN referral_depth AS rd
        ON rd.customer_id = r.referrer_customer_id
    WHERE NOT r.referred_customer_id = ANY(rd.path_ids)
      AND rd.depth < 50
)
SELECT
    depth,
    COUNT(*) AS n_customers,
    MAX(path_text) AS sample_path
FROM referral_depth
GROUP BY depth
ORDER BY depth;
""")

   depth  n_customers                                        sample_path
0      1        99432                   ffffe8b65bbe3087b653a978c870db99
1      2            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
2      3            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
3      4            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
4      5            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
5      6            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
6      7            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
7      8            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
8      9            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
9     10            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...

   depth  n_customers                                        sample_path
0      1        99432                   ffffe8b65bbe3087b653a978c870db99
1      2            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
2      3            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
3      4            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
4      5            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
5      6            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
6      7            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
7      8            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
8      9            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...
9     10            1  00012a2ce6f8dcda20d059ce98491703 -> 000161a058...

**Перевірка завершення рекурсії.** Масив `path_ids` зберігає вже відвіданих клієнтів. Якщо граф містить цикл A → B → A, повторний перехід до A не відбудеться через `NOT ... = ANY(path_ids)`. Додатково умова `depth < 50` обмежує максимальну глибину. Кореневі вузли знаходжу через `NOT EXISTS`.

## 4. Materialized View

Тепер зберігаю повний результат pipeline у матеріалізованому представленні. Унікальний індекс за `customer_id` потрібний для `REFRESH ... CONCURRENTLY`.

In [12]:
run_sql("""
CREATE MATERIALIZED VIEW mv_olist_customer_features AS
WITH
reference_date AS (
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    SELECT
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    SELECT
        s.customer_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_id, rd.as_of_date
),
stage3_cohort AS (
    SELECT
        r.*,
        DATE_TRUNC('quarter', r.first_order_date)::DATE AS cohort_quarter
    FROM stage2_rfm AS r
),
stage4_rolling_aov AS (
    SELECT
        s.customer_id,
        s.order_id,
        s.order_ts,
        s.order_total,
        AVG(s.order_total) OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts
            RANGE BETWEEN INTERVAL '30 days' PRECEDING AND CURRENT ROW
        )::NUMERIC(12, 2) AS avg_order_value_30d,
        ROW_NUMBER() OVER (
            PARTITION BY s.customer_id
            ORDER BY s.order_ts DESC, s.order_id DESC
        ) AS rn_recent
    FROM stage1_orders_total AS s
),
stage5_cancel_rate AS (
    SELECT
        customer_id,
        AVG(
            CASE WHEN order_status = 'canceled' THEN 1.0 ELSE 0.0 END
        )::NUMERIC(6, 4) AS cancellation_rate
    FROM stage1_orders_total
    GROUP BY customer_id
),
stage6_category_revenue AS (
    SELECT
        o.customer_id,
        COALESCE(p.product_category_name, '(unknown)') AS product_category_name,
        SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        )::NUMERIC(12, 2) AS category_revenue
    FROM olist_orders AS o
    JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    LEFT JOIN olist_products AS p
        ON p.product_id = oi.product_id
    GROUP BY o.customer_id, COALESCE(p.product_category_name, '(unknown)')
),
stage7_preferred_category AS (
    SELECT
        customer_id,
        product_category_name,
        category_revenue
    FROM (
        SELECT
            cr.*,
            ROW_NUMBER() OVER (
                PARTITION BY cr.customer_id
                ORDER BY cr.category_revenue DESC, cr.product_category_name
            ) AS rn
        FROM stage6_category_revenue AS cr
    ) AS ranked
    WHERE rn = 1
)
SELECT
    c.customer_id,
    c.customer_state,
    COALESCE(coh.recency_days, 9999) AS recency_days,
    COALESCE(coh.frequency, 0) AS frequency,
    COALESCE(coh.monetary, 0)::NUMERIC(12, 2) AS monetary,
    coh.first_order_date,
    coh.cohort_quarter,
    COALESCE(aov.avg_order_value_30d, 0)::NUMERIC(12, 2) AS avg_order_value_30d_recent,
    COALESCE(cancel.cancellation_rate, 0)::NUMERIC(6, 4) AS cancellation_rate,
    COALESCE(pc.product_category_name, '(none)') AS preferred_category,
    COALESCE(pc.category_revenue, 0)::NUMERIC(12, 2) AS preferred_category_revenue
FROM olist_customers AS c
LEFT JOIN stage3_cohort AS coh
    ON coh.customer_id = c.customer_id
LEFT JOIN stage4_rolling_aov AS aov
    ON aov.customer_id = c.customer_id
   AND aov.rn_recent = 1
LEFT JOIN stage5_cancel_rate AS cancel
    ON cancel.customer_id = c.customer_id
LEFT JOIN stage7_preferred_category AS pc
    ON pc.customer_id = c.customer_id;

CREATE UNIQUE INDEX idx_mv_olist_customer_features_customer_id
    ON mv_olist_customer_features (customer_id);
""")

In [13]:
run_sql("""
SELECT COUNT(*) AS n_rows FROM mv_olist_customer_features;
SELECT * FROM mv_olist_customer_features ORDER BY monetary DESC NULLS LAST, customer_id LIMIT 5;
""")

,customer_id,customer_state,recency_days,frequency,monetary,first_order_date,cohort_quarter,avg_order_value_30d_recent,cancellation_rate,preferred_category,preferred_category_revenue
0,1617b1357756262bfa56ab541c47bc16,RJ,384,1,13664.08,2017-09-29,2017-07-01,13664.08,0.0000,telefonia_fixa,13664.08
1,ec5b2ba62e574342386871631fafd3fc,ES,95,1,7274.88,2018-07-15,2018-07-01,7274.88,0.0000,telefonia_fixa,7274.88
2,c6e2731c5b391845f6800c97401a43a9,MS,613,1,6929.31,2017-02-12,2017-01-01,6929.31,0.0000,utilidades_domesticas,6929.31
3,f48d464a0baaea338cb25f816991ab1f,ES,85,1,6922.21,2018-07-25,2018-07-01,6922.21,0.0000,pcs,6922.21
4,3fd6777bbce08a352fddd04e4a7cc8f6,SP,512,1,6726.66,2017-05-24,2017-04-01,6726.66,0.0000,artes,6726.66

,customer_id,customer_state,recency_days,frequency,monetary,first_order_date,cohort_quarter,avg_order_value_30d_recent,cancellation_rate,preferred_category,preferred_category_revenue
0,1617b1357756262bfa56ab541c47bc16,RJ,384,1,13664.08,2017-09-29,2017-07-01,13664.08,0.0000,telefonia_fixa,13664.08
1,ec5b2ba62e574342386871631fafd3fc,ES,95,1,7274.88,2018-07-15,2018-07-01,7274.88,0.0000,telefonia_fixa,7274.88
2,c6e2731c5b391845f6800c97401a43a9,MS,613,1,6929.31,2017-02-12,2017-01-01,6929.31,0.0000,utilidades_domesticas,6929.31
3,f48d464a0baaea338cb25f816991ab1f,ES,85,1,6922.21,2018-07-25,2018-07-01,6922.21,0.0000,pcs,6922.21
4,3fd6777bbce08a352fddd04e4a7cc8f6,SP,512,1,6726.66,2017-05-24,2017-04-01,6726.66,0.0000,artes,6726.66

Оновлення виконую в окремому підключенні з autocommit, щоб команда `CONCURRENTLY` не опинилася всередині транзакції.

In [14]:
with engine.connect().execution_options(isolation_level="AUTOCOMMIT") as conn:
    conn.exec_driver_sql('REFRESH MATERIALIZED VIEW CONCURRENTLY mv_olist_customer_features')
print('Concurrent refresh успішно виконано.')

Concurrent refresh успішно виконано.

## 5. EXPLAIN ANALYZE + BUFFERS

Порівнюю повне обчислення ознак і пошук готового рядка в MV. Нижче зберігаю обидва плани, щоб висновки можна було перевірити за фактичними операціями та часом.

In [15]:
explain_pipeline = r"""
EXPLAIN (ANALYZE, BUFFERS)
WITH reference_date AS (
    SELECT (MAX(order_purchase_timestamp)::DATE + 1) AS as_of_date
    FROM olist_orders
),
stage1_orders_total AS (
    SELECT
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp AS order_ts,
        o.order_purchase_timestamp::DATE AS order_date,
        COALESCE(SUM(
            COALESCE(oi.price, 0) + COALESCE(oi.freight_value, 0)
        ), 0)::NUMERIC(12, 2) AS order_total
    FROM olist_orders AS o
    LEFT JOIN olist_order_items AS oi
        ON oi.order_id = o.order_id
    GROUP BY
        o.customer_id,
        o.order_id,
        o.order_status,
        o.order_purchase_timestamp
),
stage2_rfm AS (
    SELECT
        s.customer_id,
        (rd.as_of_date - MAX(s.order_date))::INTEGER AS recency_days,
        COUNT(*) AS frequency,
        SUM(s.order_total)::NUMERIC(12, 2) AS monetary,
        MIN(s.order_date) AS first_order_date
    FROM stage1_orders_total AS s
    CROSS JOIN reference_date AS rd
    GROUP BY s.customer_id, rd.as_of_date
)
SELECT *
FROM stage2_rfm
ORDER BY monetary DESC NULLS LAST
LIMIT 10;
"""
plan_pipeline = run_sql(explain_pipeline)
plan_pipeline.to_csv('explain_pipeline.csv', index=False)

                                           QUERY PLAN
0   Limit  (cost=33552.08..33552.10 rows=10 width=...
1     Buffers: shared hit=5966, temp read=3338 wri...
2     ->  Sort  (cost=33552.08..33552.58 rows=200 ...
3           Sort Key: stage2_rfm.monetary DESC NUL...
4           Sort Method: top-N heapsort  Memory: 27kB
5           Buffers: shared hit=5966, temp read=33...
6           ->  Subquery Scan on stage2_rfm  (cost...
7                 Buffers: shared hit=5966, temp r...
8                 ->  HashAggregate  (cost=33542.2...
9                       Group Key: o.customer_id, ...
10                      Batches: 21  Memory Usage:...
11                      Buffers: shared hit=5966, ...
12                      ->  Nested Loop  (cost=196...
13                            Buffers: shared hit=...
14                            ->  Aggregate  (cost...
15                                  Buffers: share...
16                                  ->  Seq Scan o...
17                                        Buffers:...
18                            ->  Finalize GroupAg...
19                                  Group Key: o.o...
20                                  Buffers: share...
21                                  ->  Gather Mer...
22                                        Workers ...
23                                        Workers ...
24                                        Buffers:...
25                                        ->  Part...
26                                              Gr...
27                                              Bu...
28                                              ->...
29                                                ...
30                                                ...
31                                                ...
32                                                ...
33                                                ...
34                                                ...
35                                                ...
36                                                ...
37                                                ...
38                                                ...
39                                                ...
40                                                ...
41                                                ...
42                                                ...
43                                          Planning:
44                              Buffers: shared hit=2
45                            Planning Time: 1.607 ms
46                         Execution Time: 749.349 ms

In [16]:
explain_mv = r"""
EXPLAIN (ANALYZE, BUFFERS)
WITH target_customer AS (SELECT customer_id
    FROM olist_customers
    ORDER BY customer_id
    LIMIT 1
)
SELECT mv.*
FROM mv_olist_customer_features AS mv
JOIN target_customer AS t
    ON t.customer_id = mv.customer_id;
"""
plan_mv = run_sql(explain_mv)
plan_mv.to_csv('explain_mv.csv', index=False)

                                           QUERY PLAN
0   Nested Loop  (cost=0.83..8.98 rows=1 width=158...
1                        Buffers: shared hit=5 read=3
2     ->  Limit  (cost=0.42..0.55 rows=1 width=32)...
3                               Buffers: shared hit=4
4           ->  Index Only Scan using olist_custom...
5                                     Heap Fetches: 1
6                               Buffers: shared hit=4
7     ->  Index Scan using idx_mv_olist_customer_f...
8           Index Cond: (customer_id = olist_custo...
9                        Buffers: shared hit=1 read=3
10                                          Planning:
11                              Buffers: shared hit=7
12                            Planning Time: 0.303 ms
13                           Execution Time: 0.137 ms

In [17]:
import re

def execution_time(plan):
    for line in plan.iloc[:, 0].astype(str):
        match = re.search(r'Execution Time:\s*([\d.]+) ms', line)
        if match: return float(match.group(1))
    return None

t1, t2 = execution_time(plan_pipeline), execution_time(plan_mv)
print(f'Pipeline: {t1} ms; MV lookup: {t2} ms')
print('Pipeline operations:', [k for k in ['HashAggregate','Hash Aggregate','Sort','Seq Scan','WindowAgg','Hash Join'] if k in '\n'.join(plan_pipeline.iloc[:,0].astype(str))])
print('MV operations:', [k for k in ['Index Scan','Seq Scan','Nested Loop','Sort'] if k in '\n'.join(plan_mv.iloc[:,0].astype(str))])

Pipeline: 749.349 ms; MV lookup: 0.137 ms
Pipeline operations: ['HashAggregate', 'Sort', 'Seq Scan']
MV operations: ['Index Scan', 'Nested Loop']

## Reflection

У цьому завданні я побудував pipeline, який перетворює таблиці замовлень на ознаки рівня клієнта. Найбільше роботи у повному варіанті створюють з’єднання замовлень із позиціями та агрегації: потрібно прочитати вихідні рядки, порахувати вартість замовлень і згрупувати їх за клієнтами. У повному pipeline додатково обчислюються віконне середнє за 30 днів і рейтинг категорій. Тому потенційно дорогими є `JOIN`, `GROUP BY`, `Sort` і віконні функції. Конкретний найдорожчий вузол я визначаю за фактичними `actual time` у виведеному вище плані; план EXPLAIN для скороченого RFM-запиту сам по собі не вимірює всі сім етапів pipeline.

Materialized View доцільна, коли одні й ті самі customer-features читаються багато разів: тоді обчислення виконуються під час створення або оновлення, а не при кожному запиті. Для історичного Olist я обрав би оновлення `on-demand`, адже дані не змінюються щохвилини. Для активного магазину доречним міг би бути щодобовий refresh. `CONCURRENTLY` дає змогу зберігати доступність читання під час оновлення, але потребує відповідного унікального індексу.

Звичайний `VIEW` я використав би для оперативного звіту, де найважливіше бачити найсвіжіші транзакції і немає великої кількості повторних запитів. Його перевага — актуальність, недолік — повторне обчислення.

Recursive CTE завершується, коли більше немає нових переходів. Перевірка `path_ids` не дозволяє повторно відвідати вузол у циклі A → B → A, а обмеження `depth < 50` додатково захищає від надмірної глибини. Важливо, що ізольований цикл без кореня не потрапить у результат поточного anchor-запиту.

Для цього pipeline головний компроміс — між `latency` та `freshness`. Я надаю перевагу швидкому читанню готових ознак, допускаючи контрольоване відставання даних. Точні часи виконання обох сценаріїв і операції `Seq Scan`, `Sort` або `Index Scan` треба оцінювати за результатами запуску клітинок EXPLAIN: на маленькій stub-схемі план може відрізнятися від реального Olist.